# Array Creation

In [1]:
import numpy as np

## Using Python sequences

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array((1,2,3))
type(b)

numpy.ndarray

In [5]:
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [6]:
type(c)

numpy.ndarray

## Using array creation objects such as `arange`, `zeros`, `ones`

In [7]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [9]:
a = np.arange(2, 10, 2)
a

array([2, 4, 6, 8])

In [11]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
linspace = np.linspace(0, 10, 5)
print(linspace)

[ 0.   2.5  5.   7.5 10. ]


In [27]:
a = np.array([1,2,3])
repeat = np.repeat(a, 3)
print(repeat)

[1 1 1 2 2 2 3 3 3]


## Using built-in special package functions

In [17]:
a = np.random.rand(4)
print(a)

[0.6036864  0.4699999  0.67112439 0.03422362]


In [24]:
a = np.random.randn(3)
print(a)

[ 0.00398803 -0.13389146 -0.63000504]


In [25]:
a = np.random.randint(1, 10, (2,3))
print(a)

[[3 5 3]
 [8 1 6]]


## Load from File

In [29]:
a = np.loadtxt('data.txt',delimiter=',')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [30]:
np.savetxt('data2.txt', ones)

## Array Properties

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [32]:
a.dtype

dtype('int64')

In [33]:
b = np.array([True, False, True])
b.dtype

dtype('bool')

In [34]:
a = np.array([[1,2,3], [4,5,6]])
a.size

6

In [35]:
a.ndim

2

In [36]:
a.itemsize

8

In [37]:
a = np.array([1,2,3])
a.itemsize # 8

8

In [38]:
a = np.array([[1,2,3], [4,5,6]])
a.nbytes # 48

48

In [40]:
a = np.array([1,2,3])
a.data # <memory at 0x7fd3ab328880>